server:
  port: 8081

spring:
  application:
    name: products-service
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.web.reactive: TRACE
