server:
  port: 8080

spring:
  application:
    name: gateway-services
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/Product/**
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/Order/**
        - id: models-service
          uri: lb://models-service
          predicates:
            - Path=/products/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/Delivery/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/